POST http://localhost:3000/brokers
Content-Type: application/json

{
  "first_name": "Ruby",
  "last_name" : "Tuesday"
}


POST  http://localhost:3000/:broker_id/quotes
Content-Type: application/json

{
  "age": 22,
  "sex": "m"
}


POST http://localhost:3000/:broker_id/policies
Content-Type: application/json

{
  "quotation_id":  "8a964dfa-4640-4ad4-824c-20ab097a983f",
  "name": "Beatrice",
  "sex": "f",
  "date_of_birth": "1987-01-01"
}

GET http://localhost:3000/brokers/:broker_id/policies?policy_id=policy_id
Content-Type: application/json
query_params = policy_id